### ISSUE TITLE
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.16.0"

### ISSUE THREAD

**Issue by sssdhjh** [emqx/MQTT-Client-Examples#105]
该项目不支持 node 18.16.0 最新版?需要降低版本才能用？
![image](https://github.com/emqx/MQTT-Client-Examples/assets/55219391/4653fba2-5868-4bcf-9a68-bd46ca075172)

**Comment by sssdhjh** [comment]
使用yarn尝试编译mqtt-client-Vue.js出现这个问题

**Comment by sssdhjh** [comment]
我不太清楚Readme.md文件中为什么推荐使用yarn工具,但我用npm install即可解决。在使用npm编译过程中同样遇到了问题，会出现“Error: error:0308010C:digital envelope routines::unsupported”提示digital envelope routines库不支持。而我在package.json文件中修改build与serve属性才解决了问题。
![image](https://github.com/emqx/MQTT-Client-Examples/assets/55219391/0568c4a4-53a3-4c64-ba9c-6bff7c2c4e39)

**Comment by 0721Betty** [comment]
> 该项目不支持 node 18.16.0 最新版?需要降低版本才能用？ ![image](https://user-images.githubusercontent.com/55219391/242275491-4653fba2-5868-4bcf-9a68-bd46ca075172.png)

Yes, the project is quite outdated. you should downgrade Node.js version.

**Comment by 0721Betty** [comment]
You can create an additional Vue 2 project on your own, as the key code for establishing a connection remains the same.
