### ISSUE TITLE
mqtt-client-Vue.js 中协议protocol端口，设置mqtt会自动转换为ws

### ISSUE THREAD

**Issue by sssdhjh** [emqx/MQTT-Client-Examples#115]
问题（question）：
我在一台机器人上部署了对应的mqtt服务器，我想使用 mqtt-client-Vue.js 案例调整参数来连接它，但出现无法连接的情况，我修改的参数如下图
![test](https://github.com/emqx/MQTT-Client-Examples/assets/55219391/313e3a1b-3e9c-4692-9d11-0d4633fcfb2d)

![test02](https://github.com/emqx/MQTT-Client-Examples/assets/55219391/957dc467-96c5-4879-a148-fba4f10a0067)

相同的，我通过MQTTX客户端来设置相同的参数，并且能成功连接上机器人来进行控制。但案例 mqtt-client-Vue.js 并没有解决我的问题，我通过console.log()方法打印protocol端口的信息竟然是ws协议，而不是我设置的mqtt协议。请问该如何解决？

**Comment by ysfscream** [comment]
@sssdhjh  您好，因为浏览器限制，您无法使用普通的 MQTT/TCP 连接，只能使用 MQTT over WebSocket 连接到 MQTT Broker。
