### ISSUE TITLE
Process Not Defined(React Js)

### ISSUE THREAD

**Issue by nkinnacostly** [emqx/MQTT-Client-Examples#119]
Uncaught ReferenceError: process is not defined
    at ./node_modules/mqtt/build/lib/client.js (client.ts:41:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/mqtt/build/mqtt.js (mqtt.ts:8:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/components/MQTTConnector/index.js (index.js:15:1)
    at options.factory (react refresh:6:1)

**Comment by XL-YiBai** [comment]
Based on the error message "Uncaught ReferenceError: process is not defined," it seems that the code is trying to access the process object which is typically available in Node.js environments but might not be available in a browser or client-side environment.

Could you please provide more detailed information about this issue? For example, the environment it's running in, how it occurred. Additionally, sharing the versions of relevant dependencies and any specific configurations might be helpful in identifying the cause of the issue.

**Comment by gesal03** [comment]
I got same error.
how to resolve this issue?
PLEASE HELP ME

node version: v 16.16.0

**Comment by dantearaujo1** [comment]
i got the same error too

**Comment by XL-YiBai** [comment]
Is this the project you are running? https://github.com/emqx/MQTT-Client-Examples/tree/master/mqtt-client-React. If not, please provide more detailed information for me to better replicate the issue. For example, the React version you are using, any additional frameworks, mqtt.js version, Node version, etc. 
I can run this project without any issues. Here are my environment details: node v16.16.0, macOS 13.4.1.

**Comment by guptaashwanee** [comment]
Use mqtt latest version 5.0.5 and import mqtt like this in browser:

```javascript
import * as mqtt from 'mqtt/dist/mqtt.min'
```

**Comment by XL-YiBai** [comment]
> Use mqtt latest version 5.0.5 and import mqtt like this in browser:
> 
> ```js
> import * as mqtt from 'mqtt/dist/mqtt.min'
> ```

Yes, after testing, it was found that in MQTT.js v5.x, we need to import mqtt: `import * as mqtt from 'mqtt/dist/mqtt.min'` like this instead of: `import mqtt from 'mqtt'`
