### ISSUE TITLE
js 使用mqtt 连接url不能用 `mqtt://${host}:${port}`？

### ISSUE THREAD

**Issue by biubiubiuu** [emqx/MQTT-Client-Examples#14]
const connectUrl = `mqtt://${host}:${port}`

在 Vue 项目中使用 MQTT文档中 const connectUrl = `ws://${host}:${port}${endpoint}`

我想用mqtt 连接不行吗？
![image](https://user-images.githubusercontent.com/41641600/104206794-edee0e00-546a-11eb-9df4-6a4774015ef4.png)
该配置文件可以连接成功的

**Comment by ysfscream** [comment]
@biubiubiuu Hi, you can't use `MQTT/TCP` to connect in the browser environment, only use `WebSocket`.
