### ISSUE TITLE
micropython通过TLS连接服务器失败

### ISSUE THREAD

**Issue by xiaomingtt** [emqx/MQTT-Client-Examples#150]
文件：mqtt-client-Micropython/pub_sub_tls.py
错误信息：Traceback (most recent call last):
  File "<stdin>", line 56, in <module>
  File "<stdin>", line 51, in run
  File "<stdin>", line 27, in connect
TypeError: unexpected keyword argument 'ssl_params'
开发环境：MicroPython v1.23.0 on 2024-06-02; Generic ESP32S3 module with Octal-SPIRAM with ESP32S3

**Comment by a1107368435** [comment]
同样的问题，请问解决了没有？

**Comment by zibuyu1995** [comment]
您好，这是因为版本不对导致，您可以参阅 1.23 以后的示例代码 https://github.com/emqx/MQTT-Client-Examples/tree/master/mqtt-client-Micropython
