### ISSUE TITLE
websocket timeout error

### ISSUE THREAD

**Issue by ARao0123** [emqx/MQTT-Client-Examples#31]
Hi, this is my first time using MQTT and I can loads of examples using TCP. But I'm trying to use websockets. I tried to connect to mqtt broker and subscribe to a topic via mqttbox and I can do it successfully. But when I try the same thing via code, I get timeout error. Details shown below:

Expected behavior: Successful connection to the mqtt broker, no errors
Actual behavior: "mqtt client encounter error connecting: network Error : dial tcp x.x.x.x:XXXX: i/o timeout"

Code snippet:

```
broker := fmt.Sprintf("ws://%s:%d/mqtt", "address", 1234)

//Create the broker
opts = mqtt.NewClientOptions()
opts.AddBroker(broker)
opts.SetClientID(fmt.Sprintf("clientID.%s", time.Now()))
opts.SetUsername(Username)
opts.SetPassword(Password)

mqttClient = mqtt.NewClient(opts)

if token := mqttClient.Connect(); token.Wait() && token.Error() != nil {
	fmt.Println(err)      // This is the error point I hit
}
```

I've tried the broker with wss and ws, no luck!
Any help/suggestions would be greatly appreciated. Thanks in advance!

**Comment by zibuyu1995** [comment]
There is no problem with your connection code, it may be due to a client network problem that caused your connection to timeout, we suggest you check the client network.
