### ISSUE TITLE
真机调试下无法连接

### ISSUE THREAD

**Issue by laolaolulu** [emqx/MQTT-Client-Examples#41]
真机调试下无法连接

**Comment by jjantura** [comment]
WeChat sample is not working on a real device. It launches, UI is shown, it looks like it's subscribing but no messages can be sent/received.

**Comment by zibuyu1995** [comment]
@laolaolulu 正机环境下，必须使用备案域名以及 443 端口连接，详细参阅 https://www.emqx.com/zh/blog/how-to-use-mqtt-in-wechat-miniprogram

**Comment by jjantura** [comment]
Ok, I think I've found it, the problem is with sandbox account - it can not send/receive messages to/from external systems.
