### ISSUE TITLE
mqtt3和mqtt5同时存在时，会出现接收消息解析失败的情况！！！

### ISSUE THREAD

**Issue by iOSbug** [emqx/MQTT-Client-Examples#55]
项目里要求同时连接mqtt3和mqtt5，如果先建立mqtt3成功，再建立mqtt5成功。此时再用mqtt3发送topic消息，再接收消息时，解析会使用mqtt5的payload里。看了代码里面的实现，在建立mqtt3或者mqtt5时，本地会存储mqtt版本号：
        if let storage = CocoaMQTTStorage() {
            storage.setMQTTVersion("5.0")
        }
       if let storage = CocoaMQTTStorage() {
            storage.setMQTTVersion("3.1.1")
       }
这是没有带clientid的，这样会导致谁后调用就会覆盖之前存储的mqtt版本号。
这样在收到消息解析payload时：
        var protocolVersion = "";
        if let storage = CocoaMQTTStorage() {
            protocolVersion = storage.queryMQTTVersion()
        }

        if (protocolVersion == "5.0"){
            let data = MqttDecodePublish()
            data.decodePublish(fixedHeader: packetFixedHeaderType ,publishData: bytes)
            pos += 1

            if(data.propertyLength != 0){
                pos += data.propertyLength!
            }

            // MQTT 5.0
            self.mqtt5Topic = data.topic
            self.packetIdentifier = data.packetIdentifier
            self.publishRecProperties = data

        }else{
            // MQTT 3.1.1
            topic = NSString(bytes: [UInt8](bytes[2...(pos-1)]), length: Int(len), encoding: String.Encoding.utf8.rawValue)! as String
        }
这样就会导致mqtt3发送的消息，会进入mqtt5的解析中。请确认如何修正

**Comment by leeway1208** [comment]
Hello. The function of using mqtt3 and mqtt5 in parallel is not supported currently,  please wait for our future updates soon. Thanks.
