### ISSUE TITLE
真机无法连接，域名已备案、端口8084。版本试了很多 v4.2.1、v4.2.0、v4.1.0 和 v2.18.8

### ISSUE THREAD

**Issue by hahagod** [emqx/MQTT-Client-Examples#65]
22年4月份真机是没问题的，下半年突然真机无法连接了。

![image](https://user-images.githubusercontent.com/11895727/215302023-df414c71-687f-48d3-97db-bd0d0c4429cd.png)

**Comment by XL-YiBai** [comment]
请问您这边的具体运行环境是怎样的？如何引入的mqtt.js？微信小程序工具的版本？使用的IOS还是安卓手机？

我这边原生小程序使用本地引入mqtt.min.js，刚刚测试了一下您这边说的这几个版本，在真机调试的情况下都是可以连接成功的。

**Comment by XL-YiBai** [comment]
请问您这边的具体运行环境是怎样的？如何引入的mqtt.js？微信小程序工具的版本？使用的IOS还是安卓手机？

我这边原生小程序使用本地引入mqtt.min.js，刚刚测试了一下您这边说的这几个版本，在真机调试的情况下都是可以连接成功的。
