### ISSUE TITLE
esp8266_connect_mqtt_via_tls.ino, Compilation error: 'class BearSSL::WiFiClientSecure' has no member named 'setCACert'

### ISSUE THREAD

**Issue by lybce** [emqx/MQTT-Client-Examples#75]
Hi, I copy&paste your .ino code but Arduino IDE report this error:
Compilation error: 'class BearSSL::WiFiClientSecure' has no member named 'setCACert'

Do you have same issue ?

Thanks

**Comment by zibuyu1995** [comment]
Thank you for your feedback, we need some time to verify it.

**Comment by Jinxuyang** [comment]
https://stackoverflow.com/questions/67962746/class-bearsslwificlientsecure-has-no-member-named-loadcertificate
This might help you

**Comment by zibuyu1995** [comment]
We have updated the code to work with version 3.x, see the https://github.com/emqx/MQTT-Client-Examples/blob/master/mqtt-client-ESP8266/esp8266_connect_mqtt_via_tls.ino
