### ISSUE TITLE
mqtt / nuxt 3 - Uncaught ReferenceError

### ISSUE THREAD

**Issue by briankandersen** [emqx/MQTT-Client-Examples#81]
As soon as I try to call the mqtt connect function, I get this error in the console:

Uncaught ReferenceError: Buffer is not defined
    at node_modules/mqtt-packet/constants.js

Has anybody successfully gotten mqttjs to work in nuxt 3?

**Comment by 0721Betty** [comment]
> As soon as I try to call the mqtt connect function, I get this error in the console:
> 
> Uncaught ReferenceError: Buffer is not defined at node_modules/mqtt-packet/constants.js
> 
> Has anybody successfully gotten mqttjs to work in nuxt 3?


Hope the following code is useful to you

```js
import * as mqtt from "mqtt/dist/mqtt.min";

if (process.client) {
  const client = mqtt.connect("ws://broker.emqx.io:8083/mqtt");
  console.log("mqtt client", client, mqtt);
}
```

in addition, refer to the `MQTT.js` issue: https://github.com/mqttjs/MQTT.js/issues/1269, you need do like this:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/48433973/233827572-d1c1cb4b-c8e7-4bfd-b4ad-4edf504f6ced.png">

**Comment by briankandersen** [comment]
Thank you Betty, that works perfectly :)
